In [1]:
#from pandas import read_csv
from pandas import datetime
import pandas as pd
import numpy as np
from matplotlib import pyplot
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn import metrics
%matplotlib inline

reading in eps data

In [2]:
data = pd.read_csv('eps_nifty50.csv')
data

,Company,Ticker,Sep-19,Jun-19,Mar-19,Dec-18,Sep-18,Jun-18,Mar-18,Dec-17,...,Sep-10,Jun-10,Mar-10,Dec-09,Sep-09,Jun-09,Mar-09,Dec-08,Sep-08,Jun-08
0,Adani Ports & Special Economic Zone Ltd.,ADSEZ IS Equity,2.35,2.36,3.26,4.42,3.32,1.74,3.38,2.54,...,1.06,5.27,2.40,0.81,0.87,4.26,3.77,2.52,2.80,2.42
1,Asian Paints Ltd.,APNT IS Equity,8.24,6.80,4.98,6.58,5.01,5.65,5.12,5.51,...,20.45,20.95,16.40,18.63,25.91,17.14,10.26,5.22,12.69,10.22
2,Axis Bank Ltd.,AXSB IS Equity,-0.43,5.29,5.85,6.54,3.07,2.73,-8.53,3.00,...,18.01,18.26,18.92,16.29,14.64,15.64,16.20,13.95,11.23,9.22
3,Bajaj Auto Ltd.,BJAUT IS Equity,48.50,38.90,45.10,38.10,39.80,38.50,37.30,32.90,...,23.60,20.40,18.30,16.40,13.90,20.30,9.00,11.40,12.80,12.10
4,Bajaj Finance Ltd.,BAF IS Equity,23.83,19.49,19.31,17.74,15.97,14.49,12.92,12.03,...,14.42,12.78,5.88,7.46,5.93,4.16,4.12,3.08,1.25,0.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

removing extra NaN rows that came in the datframe while reading from csv

In [3]:
data.drop(index=list(range(48, 997)),inplace=True)
data.drop('Company',inplace=True,axis=1)

making a list of column names

In [4]:
column_name = data.columns[1:31].tolist()

predicting eps using linear regression

In [5]:
pred_dict = {}
std_dict = {}
for i in range(len(data)):
    prediction=[]
    stddev=[]
    for j in range(1,31):
        series = data.iloc[i][(j+1):(j+17)]
        X = np.asarray([i for i in range(16)]).reshape(-1,1)
        y = series.copy()
        X_pred =np.asarray([16]).reshape(-1,1)
        regressor = LinearRegression()  
        regressor.fit(X, y)
        y_pred = regressor.predict(X_pred)
        std = np.std(series)
        prediction.append(y_pred[0])
        stddev.append(std)
    pred_dict[data.loc[i][0]] = prediction
    std_dict[data.loc[i][0]] = stddev
pred = pd.DataFrame.from_dict(pred_dict, orient='index',columns=column_name)
stdev = pd.DataFrame.from_dict(std_dict, orient='index',columns=column_name)
#pred.head()

saving dataframes to csv

In [6]:
pred.to_csv(r'linear_reg_predicted_eps.csv')

In [7]:
stdev.to_csv(r'std_dev_eps_predicted.csv')